### ISSUE TITLE
pass param to construct

### ISSUE THREAD

**Issue by NVD-R** [thecodingmachine/best-practices#24]
hi,
i write a class like that:
`
class SERVICE{
public function __construct($a, UserRepository $repository)
    {
        $this->repository = $repository;
        $this->relations = [['\Api\Users\Models\Client', 'clients', '$a']];
        $this->events = [ ];
    }
...
}
`

and i used those class like that:
`
use SERVICE;
class TEST{
public function __construct(SERVICE $service)
    {
        $this->service = $service;
    }
}
` 
and i have error:

> Unresolvable dependency resolving [Parameter #0 [ $a ]]

how can i sen parameter in this way?

**Comment by moufmouf** [comment]
Sorry, reading your comment only now.
I guess you have found your answer since then. For this kind of questions, a great place to ask is https://www.reddit.com/r/PHPhelp/
